apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "micro-ddns.configMapName" . }}
  labels:
    {{- include "micro-ddns.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ .Values.ddnsConfig | nindent 4 }}
