#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1

NAME="micro-ddns"
PROG="/usr/bin/micro-ddns"
CONFIG="/etc/micro-ddns/config.yaml"
ARGS="run -c $CONFIG"

start_service() {
    procd_open_instance
    procd_set_param command "$PROG" $ARGS
    procd_set_param file "$CONFIG"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
